name: Node CI

on:
  push:
    paths:
      - 'node/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node

    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        npm i -g yarn
        yarn

    - name: Validate
      run: |
        yarn test

    - name: Build and Deploy (NPM)
      run: |
        yarn build
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Build and Deploy (GH)
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}