name: Python CI

on:
  push:
    paths:
      - 'python/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: Gr1N/setup-poetry@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        poetry env info
        poetry install

    - name: Validate
      run: |
        poetry check
        poetry run pytest

    - name: Build
      run: poetry build

    - name: Publish
      run: poetry publish -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
